#max_length
CONST_NAME_LENGTH = 100
CONST_DESC_LENGTH = 500
CONST_FIRST_NAME_LENGTH = 100
CONST_LAST_NAME_LENGTH = 100
CONST_USER_NAME_LENGTH = 150
CONST_PASSWORD_LENGTH = 128
CONST_CHOICES_TODO_STATUS_LENGTH = 20

#error_code
CONST_ERROR_RESPONSE_CODE = 400
CONST_INVALID_SERIALZER_CODE = 1001

#templates
CONST_ERROR_INVALID_PASSWORD = 'Invalid Pasword'
CONST_ERROR_INVALID_USERNAME = 'Invalid Username'

CONST_ERROR_MESSAGE_TEMPLATE = {}
CONST_ERROR_MESSAGE_TEMPLATE[CONST_ERROR_INVALID_PASSWORD] = CONST_ERROR_INVALID_PASSWORD
CONST_ERROR_MESSAGE_TEMPLATE[CONST_ERROR_INVALID_USERNAME] = CONST_ERROR_INVALID_USERNAME

#choices
CONST_CHOICES_TODO_STATUS_PENDING = 'pending'
CONST_CHOICES_TODO_STATUS_COMPLETED = 'completed'
CONST_CHOICES_TODO_STATUS = (
    (CONST_CHOICES_TODO_STATUS_PENDING, CONST_CHOICES_TODO_STATUS_PENDING),
    (CONST_CHOICES_TODO_STATUS_COMPLETED, CONST_CHOICES_TODO_STATUS_COMPLETED)
)
