# Generated by Django 2.2 on 2020-01-13 18:40

import api.models.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200112_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=api.models.services.now)),
                ('deleted_at', models.DateTimeField(db_index=True, default=None, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notes', models.TextField(max_length=500, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
                'index_together': {('id', 'is_deleted', 'modified_at')},
            },
        ),
    ]
