# Generated by Django 2.2 on 2020-01-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
